server:  port: 8080spring:  application:    name: project-base  datasource:    username: test_user
management:  endpoints:    web:      exposure:        include: "*"application:  util:    message: Test